language: python
python:
  # - "2.6"
  # - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: 
    - sudo apt-get update
    - pip install -r requirements.txt

# command to run tests
script: pytest
