language: python
python:
  # - "2.6"
  # - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: 
    - sudo apt-get update
    - sudo apt-get install build-essential libhdf5-7 python-dev
    - pip install -r requirements.txt
    - wget https://sourceforge.net/projects/simupop/files/simupop/1.1.7/simuPOP-1.1.7-src.tar.gz
    - tar zxf simuPOP-1.1.7.tar.gz
    - cd simuPOP-1.1.7
    - python setup.py install

# command to run tests
script: pytest
